# Generated by Django 4.2.7 on 2023-11-12 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=256)),
                ('body', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TK', 'Танк'), ('HL', 'Лекарь'), ('DD', 'Боец'), ('TD', 'Торговец'), ('GM', 'Мастер гильдии'), ('QG', 'Квестодатель'), ('BM', 'Кузнец'), ('TN', 'Кожевник'), ('PM', 'Зельевар'), ('SM', 'Мастер заклинаний')], default='DD', max_length=2)),
                ('confirmed', models.BooleanField(default=False)),
                ('auth_code', models.CharField(max_length=6, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.announcement')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.player')),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.player'),
        ),
    ]
