# Generated by Django 4.2.7 on 2023-11-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('NC', 'Не рассмотрено'), ('AG', 'Принято'), ('DC', 'Отклонено')], default='NC', max_length=2),
        ),
    ]
